spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
  liquibase:
    enabled: false
  h2:
    console:
      enabled: false

server:
  port: 0
  servlet:
    context-path: /api/v1

ENCRYPTION_KEY: "test-encryption-key-32-characters!"
SERVER_PORT: 8080
SERVER_CONTEXT_PATH: /api/v1
APP_EXPIRY_DATE: 3

app:
  encryption:
    key: "test-encryption-key-32-characters!"
  expiry_date: 3
  rest_path: /api/v1
  page_size: 10

logging:
  level:
    root: WARN
    kg.manurov.bankmvc: INFO
    org.hibernate.SQL: WARN
    org.springframework.test: WARN
    org.springframework.web: WARN