server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

spring:
  application:
    name: bank-cards
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public

  liquibase:
    change-log: classpath:db/migrations/master.yaml
    enabled: true

app:
  encryption:
    key: ${ENCRYPTION_KEY}
  expiry_date: ${APP_EXPIRY_DATE}
  rest_path: ${SERVER_CONTEXT_PATH}